version: '2'
services:
    unistrapg-app:
        image: unistrapg
        external_links:
            - unistrapg-mysql:mysql
            - unistrapg-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/unistrapg?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    unistrapg-mysql:
        extends:
            file: mysql.yml
            service: unistrapg-mysql
    unistrapg-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: unistrapg-elasticsearch
